// try {
//     //simulate the error 
//     throw new Error("Something went wrong");
// }
// catch(error){
//     console.error('Caught an error : ' , error)
// }

console.log(Math.floor(18/10))